### ISSUE TITLE
can we remove port 19092 from expose ports list and from KAFKA_LISTENERS for node2, as it only acts as a broker not controller

### ISSUE THREAD

**Issue by moglideveloper** [izzyacademy/kafka-in-a-box#1]
https://github.com/izzyacademy/kafka-in-a-box/blob/432aba28fc1e010ba5ec7dad39a054649b6d554d/compose/kraft/multi-node-docker-compose.yml#L63

https://github.com/izzyacademy/kafka-in-a-box/blob/432aba28fc1e010ba5ec7dad39a054649b6d554d/compose/kraft/multi-node-docker-compose.yml#L55

Kindlly suggest, if port 19092 can be removed from expose ports list and from KAFKA_LISTENERS for node2, as it only acts as a broker not controller.

**Comment by izzyacademy** [comment]
@moglideveloper thank you for reporting the issue. I will be reviewing it soon and the yaml file and any other related artifacts will be update accordingly. 

Thanks for the feedback

**Comment by izzyacademy** [comment]
@moglideveloper the issue has been resolved. Thanks for sharing this feedback.

**Comment by techLeadAtLogicOverCode** [comment]
19092 is still there in KAFKA_LISTENERS

https://github.com/izzyacademy/kafka-in-a-box/blob/f5c07541dcbb528256b58f77d8a219fd25ef4b07/compose/kraft/multi-node-docker-compose.yml#L62
