### ISSUE TITLE
Kafka Helm Charts with statefulsets

### ISSUE THREAD

**Issue by bharathreddy901** [izzyacademy/kafka-in-a-box#5]
Hi  Israel Ekpo,

Kafka helm charts shared in GitHub with deployment state. Can we get helm charts with statefulset.

Thanks,
Bharath Reddy

**Comment by izzyacademy** [comment]
At this time, there is no plan to create Helm charts for Stateful Sets 

I am open to pull requests if you have bandwidth to develop the infra needed for Stateful sets.

If you can create one and submit a PR that will be great. This was initially designed to show how you can run Kafka Ecosystem on containers for local development and not intended for production deployment. So I did not have bandwidth to make it a StatefulSet at that time. Nevertheless I think Stateful sets will be a great idea.

Stateful Sets will require additional work to discover host names, configure volumes and other infra necessary to support the Zookeeper, Broker and other pods. Right now this is easier to implement with just static pod names.

**Comment by bharathreddy901** [comment]
Thank you Israel Ekpo for the update.
